# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'export.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_exp_fields(object):
    def setupUi(self, Dialog_exp_fields):
        Dialog_exp_fields.setObjectName("Dialog_exp_fields")
        Dialog_exp_fields.setWindowModality(QtCore.Qt.WindowModal)
        Dialog_exp_fields.resize(400, 563)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_exp_fields)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(Dialog_exp_fields)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(11, -1, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.bot_toggle_select_all = QtWidgets.QPushButton(Dialog_exp_fields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_toggle_select_all.sizePolicy().hasHeightForWidth())
        self.bot_toggle_select_all.setSizePolicy(sizePolicy)
        self.bot_toggle_select_all.setMaximumSize(QtCore.QSize(16, 16))
        self.bot_toggle_select_all.setText("")
        self.bot_toggle_select_all.setObjectName("bot_toggle_select_all")
        self.horizontalLayout_7.addWidget(self.bot_toggle_select_all)
        self.label_toggle_select_all = QtWidgets.QLabel(Dialog_exp_fields)
        self.label_toggle_select_all.setAlignment(QtCore.Qt.AlignCenter)
        self.label_toggle_select_all.setObjectName("label_toggle_select_all")
        self.horizontalLayout_7.addWidget(self.label_toggle_select_all)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.line_2 = QtWidgets.QFrame(Dialog_exp_fields)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidget = MyTreeWidget(Dialog_exp_fields)
        self.treeWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeWidget.setIndentation(40)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.treeWidget.header().setVisible(False)
        self.horizontalLayout.addWidget(self.treeWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(Dialog_exp_fields)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.dateEdit_exp_dal_wid = QtWidgets.QWidget(Dialog_exp_fields)
        self.dateEdit_exp_dal_wid.setObjectName("dateEdit_exp_dal_wid")
        self.horizontalLayout_4.addWidget(self.dateEdit_exp_dal_wid)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(Dialog_exp_fields)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.dateEdit_exp_al_wid = QtWidgets.QWidget(Dialog_exp_fields)
        self.dateEdit_exp_al_wid.setObjectName("dateEdit_exp_al_wid")
        self.horizontalLayout_5.addWidget(self.dateEdit_exp_al_wid)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.radio_exp_untill_this_month = QtWidgets.QRadioButton(Dialog_exp_fields)
        self.radio_exp_untill_this_month.setObjectName("radio_exp_untill_this_month")
        self.verticalLayout_4.addWidget(self.radio_exp_untill_this_month)
        self.radio_exp_just_this_month = QtWidgets.QRadioButton(Dialog_exp_fields)
        self.radio_exp_just_this_month.setObjectName("radio_exp_just_this_month")
        self.verticalLayout_4.addWidget(self.radio_exp_just_this_month)
        self.radio_exp_all = QtWidgets.QRadioButton(Dialog_exp_fields)
        self.radio_exp_all.setObjectName("radio_exp_all")
        self.verticalLayout_4.addWidget(self.radio_exp_all)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(93, 203, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, -1, -1, 16)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.bot_ok_export = QtWidgets.QPushButton(Dialog_exp_fields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_ok_export.sizePolicy().hasHeightForWidth())
        self.bot_ok_export.setSizePolicy(sizePolicy)
        self.bot_ok_export.setMaximumSize(QtCore.QSize(75, 23))
        self.bot_ok_export.setDefault(True)
        self.bot_ok_export.setObjectName("bot_ok_export")
        self.verticalLayout_6.addWidget(self.bot_ok_export)
        self.bot_canc_export = QtWidgets.QPushButton(Dialog_exp_fields)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_canc_export.sizePolicy().hasHeightForWidth())
        self.bot_canc_export.setSizePolicy(sizePolicy)
        self.bot_canc_export.setMaximumSize(QtCore.QSize(75, 23))
        self.bot_canc_export.setObjectName("bot_canc_export")
        self.verticalLayout_6.addWidget(self.bot_canc_export)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(Dialog_exp_fields)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Dialog_exp_fields)
        QtCore.QMetaObject.connectSlotsByName(Dialog_exp_fields)

    def retranslateUi(self, Dialog_exp_fields):
        _translate = QtCore.QCoreApplication.translate
        Dialog_exp_fields.setWindowTitle(_translate("Dialog_exp_fields", "Documenti da Esportare"))
        self.label_7.setText(_translate("Dialog_exp_fields", "Selezionare i documenti da Esportare in CSV"))
        self.label_toggle_select_all.setText(_translate("Dialog_exp_fields", "Seleziona Tutto"))
        self.treeWidget.setSortingEnabled(True)
        self.label.setText(_translate("Dialog_exp_fields", "Dal:"))
        self.label_2.setText(_translate("Dialog_exp_fields", "Al:"))
        self.radio_exp_untill_this_month.setText(_translate("Dialog_exp_fields", "Fino al Mese Corrente"))
        self.radio_exp_just_this_month.setText(_translate("Dialog_exp_fields", "Solo Mese Corrente"))
        self.radio_exp_all.setText(_translate("Dialog_exp_fields", "Tutte le date"))
        self.bot_ok_export.setText(_translate("Dialog_exp_fields", "Ok"))
        self.bot_canc_export.setText(_translate("Dialog_exp_fields", "Cancel"))


from kwidget.my_tree_widget.MyTreeWidget import MyTreeWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_exp_fields = QtWidgets.QDialog()
    ui = Ui_Dialog_exp_fields()
    ui.setupUi(Dialog_exp_fields)
    Dialog_exp_fields.show()
    sys.exit(app.exec_())
