# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(887, 940)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.sigla = QtWidgets.QWidget()
        self.sigla.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.148, y2:1, stop:0 rgba(0, 255, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"\n"
"\n"
"")
        self.sigla.setObjectName("sigla")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.sigla)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame = QtWidgets.QFrame(self.sigla)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6.addWidget(self.frame, 0, 0, 1, 1)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        spacerItem = QtWidgets.QSpacerItem(784, 641, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem1)
        self.waiting_spinner = MySp(self.sigla)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.waiting_spinner.sizePolicy().hasHeightForWidth())
        self.waiting_spinner.setSizePolicy(sizePolicy)
        self.waiting_spinner.setMinimumSize(QtCore.QSize(100, 100))
        self.waiting_spinner.setMaximumSize(QtCore.QSize(100, 394))
        self.waiting_spinner.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.waiting_spinner.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.waiting_spinner.setObjectName("waiting_spinner")
        self.horizontalLayout_32.addWidget(self.waiting_spinner)
        self.verticalLayout_19.addLayout(self.horizontalLayout_32)
        self.gridLayout_6.addLayout(self.verticalLayout_19, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.sigla)
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.main_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.main_page)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridLayout = QtWidgets.QGridLayout(self.tab1)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_calendar = QtWidgets.QFrame(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_calendar.sizePolicy().hasHeightForWidth())
        self.frame_calendar.setSizePolicy(sizePolicy)
        self.frame_calendar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_calendar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_calendar.setObjectName("frame_calendar")
        self.gridLayout.addWidget(self.frame_calendar, 0, 0, 1, 1)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_7 = QtWidgets.QLabel(self.tab1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_16.addWidget(self.label_7)
        self.tableWidget_info_ospite = QtWidgets.QTableWidget(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_info_ospite.sizePolicy().hasHeightForWidth())
        self.tableWidget_info_ospite.setSizePolicy(sizePolicy)
        self.tableWidget_info_ospite.setMinimumSize(QtCore.QSize(300, 0))
        self.tableWidget_info_ospite.setMaximumSize(QtCore.QSize(300, 240))
        self.tableWidget_info_ospite.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_info_ospite.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_info_ospite.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_info_ospite.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_info_ospite.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_info_ospite.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_info_ospite.setShowGrid(False)
        self.tableWidget_info_ospite.setObjectName("tableWidget_info_ospite")
        self.tableWidget_info_ospite.setColumnCount(2)
        self.tableWidget_info_ospite.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info_ospite.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info_ospite.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info_ospite.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info_ospite.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info_ospite.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info_ospite.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info_ospite.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info_ospite.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_info_ospite.setHorizontalHeaderItem(1, item)
        self.tableWidget_info_ospite.horizontalHeader().setVisible(False)
        self.tableWidget_info_ospite.horizontalHeader().setDefaultSectionSize(95)
        self.tableWidget_info_ospite.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_info_ospite.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_16.addWidget(self.tableWidget_info_ospite)
        self.horizontalLayout_26.addLayout(self.verticalLayout_16)
        self.line_5 = QtWidgets.QFrame(self.tab1)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_26.addWidget(self.line_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.tab1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.tableWidget_stat = QtWidgets.QTableWidget(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_stat.sizePolicy().hasHeightForWidth())
        self.tableWidget_stat.setSizePolicy(sizePolicy)
        self.tableWidget_stat.setMaximumSize(QtCore.QSize(300, 220))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.tableWidget_stat.setPalette(palette)
        self.tableWidget_stat.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget_stat.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_stat.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget_stat.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_stat.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_stat.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_stat.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_stat.setShowGrid(False)
        self.tableWidget_stat.setCornerButtonEnabled(False)
        self.tableWidget_stat.setObjectName("tableWidget_stat")
        self.tableWidget_stat.setColumnCount(2)
        self.tableWidget_stat.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stat.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stat.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stat.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stat.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stat.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stat.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stat.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stat.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_stat.setHorizontalHeaderItem(1, item)
        self.tableWidget_stat.horizontalHeader().setVisible(False)
        self.tableWidget_stat.horizontalHeader().setDefaultSectionSize(115)
        self.tableWidget_stat.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_stat.horizontalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.tableWidget_stat)
        self.horizontalLayout_26.addLayout(self.verticalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem2)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bot_spese = ColorButton(self.tab1)
        self.bot_spese.setMinimumSize(QtCore.QSize(75, 0))
        self.bot_spese.setMaximumSize(QtCore.QSize(75, 16777215))
        self.bot_spese.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bot_spese.setStyleSheet("")
        self.bot_spese.setObjectName("bot_spese")
        self.horizontalLayout.addWidget(self.bot_spese)
        self.bot_note = ColorButton(self.tab1)
        self.bot_note.setMinimumSize(QtCore.QSize(75, 0))
        self.bot_note.setMaximumSize(QtCore.QSize(75, 16777215))
        self.bot_note.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bot_note.setObjectName("bot_note")
        self.horizontalLayout.addWidget(self.bot_note)
        self.verticalLayout_11.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, 22, -1)
        self.horizontalLayout_7.setSpacing(4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.tab1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.label_stagione = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_stagione.sizePolicy().hasHeightForWidth())
        self.label_stagione.setSizePolicy(sizePolicy)
        self.label_stagione.setMinimumSize(QtCore.QSize(90, 0))
        self.label_stagione.setStyleSheet("font: 75 18pt \"MS Sans Serif\";\n"
"color: rgb(170, 0, 0);")
        self.label_stagione.setAlignment(QtCore.Qt.AlignCenter)
        self.label_stagione.setObjectName("label_stagione")
        self.horizontalLayout_7.addWidget(self.label_stagione)
        self.verticalLayout_11.addLayout(self.horizontalLayout_7)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem3)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.bot_cancella = QtWidgets.QPushButton(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_cancella.sizePolicy().hasHeightForWidth())
        self.bot_cancella.setSizePolicy(sizePolicy)
        self.bot_cancella.setMinimumSize(QtCore.QSize(131, 51))
        self.bot_cancella.setMaximumSize(QtCore.QSize(131, 51))
        self.bot_cancella.setObjectName("bot_cancella")
        self.verticalLayout_10.addWidget(self.bot_cancella)
        self.bot_prenota = QtWidgets.QPushButton(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_prenota.sizePolicy().hasHeightForWidth())
        self.bot_prenota.setSizePolicy(sizePolicy)
        self.bot_prenota.setMinimumSize(QtCore.QSize(131, 51))
        self.bot_prenota.setMaximumSize(QtCore.QSize(131, 51))
        self.bot_prenota.setObjectName("bot_prenota")
        self.verticalLayout_10.addWidget(self.bot_prenota)
        self.horizontalLayout_22.addLayout(self.verticalLayout_10)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_22.addLayout(self.verticalLayout_18)
        self.bot_esporta = QtWidgets.QPushButton(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_esporta.sizePolicy().hasHeightForWidth())
        self.bot_esporta.setSizePolicy(sizePolicy)
        self.bot_esporta.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.bot_esporta.setObjectName("bot_esporta")
        self.horizontalLayout_22.addWidget(self.bot_esporta)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem4)
        self.verticalLayout_12.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_26.addLayout(self.verticalLayout_12)
        self.gridLayout.addLayout(self.horizontalLayout_26, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.line_2 = QtWidgets.QFrame(self.tab2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_8.addWidget(self.line_2)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(32, -1, -1, 21)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.tab2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.spinBox_ospiti = QtWidgets.QSpinBox(self.tab2)
        self.spinBox_ospiti.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_ospiti.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBox_ospiti.setMinimum(1)
        self.spinBox_ospiti.setMaximum(5)
        self.spinBox_ospiti.setObjectName("spinBox_ospiti")
        self.horizontalLayout_8.addWidget(self.spinBox_ospiti)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_8)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(32, -1, -1, -1)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.tab2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.spinBox_bambini = QtWidgets.QSpinBox(self.tab2)
        self.spinBox_bambini.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_bambini.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBox_bambini.setObjectName("spinBox_bambini")
        self.horizontalLayout_9.addWidget(self.spinBox_bambini)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_9)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_16.addLayout(self.horizontalLayout_10)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_24.addLayout(self.verticalLayout_8)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem8)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setContentsMargins(-1, 16, 32, 16)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.radio_colazione = QtWidgets.QRadioButton(self.tab2)
        self.radio_colazione.setObjectName("radio_colazione")
        self.verticalLayout_15.addWidget(self.radio_colazione)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem9)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label = QtWidgets.QLabel(self.tab2)
        self.label.setObjectName("label")
        self.horizontalLayout_23.addWidget(self.label)
        self.spinBox_importo = QtWidgets.QSpinBox(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_importo.sizePolicy().hasHeightForWidth())
        self.spinBox_importo.setSizePolicy(sizePolicy)
        self.spinBox_importo.setMinimumSize(QtCore.QSize(48, 0))
        self.spinBox_importo.setMaximumSize(QtCore.QSize(48, 16777215))
        self.spinBox_importo.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_importo.setProperty("value", 40)
        self.spinBox_importo.setObjectName("spinBox_importo")
        self.horizontalLayout_23.addWidget(self.spinBox_importo)
        self.verticalLayout_15.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24.addLayout(self.verticalLayout_15)
        self.verticalLayout_9.addLayout(self.horizontalLayout_24)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem10)
        self.line_4 = QtWidgets.QFrame(self.tab2)
        self.line_4.setMinimumSize(QtCore.QSize(641, 0))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_9.addWidget(self.line_4)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setContentsMargins(-1, -1, -1, 18)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem11)
        self.label_12 = QtWidgets.QLabel(self.tab2)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.plainTextEdit_note = QtWidgets.QPlainTextEdit(self.tab2)
        self.plainTextEdit_note.setObjectName("plainTextEdit_note")
        self.verticalLayout_4.addWidget(self.plainTextEdit_note)
        self.horizontalLayout_28.addLayout(self.verticalLayout_4)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem13)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_13 = QtWidgets.QLabel(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(66, 21))
        self.label_13.setMaximumSize(QtCore.QSize(66, 21))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_17.addWidget(self.label_13)
        self.lineEdit_lordo = QtWidgets.QLineEdit(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_lordo.sizePolicy().hasHeightForWidth())
        self.lineEdit_lordo.setSizePolicy(sizePolicy)
        self.lineEdit_lordo.setMinimumSize(QtCore.QSize(83, 21))
        self.lineEdit_lordo.setMaximumSize(QtCore.QSize(83, 21))
        self.lineEdit_lordo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_lordo.setReadOnly(True)
        self.lineEdit_lordo.setObjectName("lineEdit_lordo")
        self.horizontalLayout_17.addWidget(self.lineEdit_lordo)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_17)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem14)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem15)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_16 = QtWidgets.QLabel(self.tab2)
        self.label_16.setMinimumSize(QtCore.QSize(66, 21))
        self.label_16.setMaximumSize(QtCore.QSize(66, 21))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_25.addWidget(self.label_16)
        self.lineEdit_netto = QtWidgets.QLineEdit(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_netto.sizePolicy().hasHeightForWidth())
        self.lineEdit_netto.setSizePolicy(sizePolicy)
        self.lineEdit_netto.setMinimumSize(QtCore.QSize(83, 21))
        self.lineEdit_netto.setMaximumSize(QtCore.QSize(83, 21))
        self.lineEdit_netto.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_netto.setReadOnly(True)
        self.lineEdit_netto.setObjectName("lineEdit_netto")
        self.horizontalLayout_25.addWidget(self.lineEdit_netto)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_25)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem16)
        self.verticalLayout_17.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_17 = QtWidgets.QLabel(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(66, 21))
        self.label_17.setMaximumSize(QtCore.QSize(66, 21))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_20.addWidget(self.label_17)
        self.lineEdit_numeroGiorni = QtWidgets.QLineEdit(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_numeroGiorni.sizePolicy().hasHeightForWidth())
        self.lineEdit_numeroGiorni.setSizePolicy(sizePolicy)
        self.lineEdit_numeroGiorni.setMinimumSize(QtCore.QSize(83, 21))
        self.lineEdit_numeroGiorni.setMaximumSize(QtCore.QSize(83, 21))
        self.lineEdit_numeroGiorni.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_numeroGiorni.setReadOnly(True)
        self.lineEdit_numeroGiorni.setObjectName("lineEdit_numeroGiorni")
        self.horizontalLayout_20.addWidget(self.lineEdit_numeroGiorni)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_20)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem17)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem18)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_18 = QtWidgets.QLabel(self.tab2)
        self.label_18.setMinimumSize(QtCore.QSize(66, 21))
        self.label_18.setMaximumSize(QtCore.QSize(66, 21))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_31.addWidget(self.label_18)
        self.lineEdit_tax = QtWidgets.QLineEdit(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_tax.sizePolicy().hasHeightForWidth())
        self.lineEdit_tax.setSizePolicy(sizePolicy)
        self.lineEdit_tax.setMinimumSize(QtCore.QSize(83, 21))
        self.lineEdit_tax.setMaximumSize(QtCore.QSize(83, 21))
        self.lineEdit_tax.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_tax.setReadOnly(True)
        self.lineEdit_tax.setObjectName("lineEdit_tax")
        self.horizontalLayout_31.addWidget(self.lineEdit_tax)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_31)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem19)
        self.verticalLayout_17.addLayout(self.horizontalLayout_30)
        self.verticalLayout_5.addLayout(self.verticalLayout_17)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.bot_modifica = QtWidgets.QPushButton(self.tab2)
        self.bot_modifica.setObjectName("bot_modifica")
        self.horizontalLayout_21.addWidget(self.bot_modifica)
        self.bot_salva = QtWidgets.QPushButton(self.tab2)
        self.bot_salva.setObjectName("bot_salva")
        self.horizontalLayout_21.addWidget(self.bot_salva)
        self.bot_annulla = QtWidgets.QPushButton(self.tab2)
        self.bot_annulla.setObjectName("bot_annulla")
        self.horizontalLayout_21.addWidget(self.bot_annulla)
        self.bot_checkDisp = QtWidgets.QPushButton(self.tab2)
        self.bot_checkDisp.setObjectName("bot_checkDisp")
        self.horizontalLayout_21.addWidget(self.bot_checkDisp)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_28.addLayout(self.verticalLayout_5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_28)
        self.gridLayout_2.addLayout(self.verticalLayout_9, 3, 0, 2, 2)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem21)
        self.line_3 = QtWidgets.QFrame(self.tab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setMinimumSize(QtCore.QSize(641, 0))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_14.addWidget(self.line_3)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem22)
        self.gridLayout_2.addLayout(self.verticalLayout_14, 1, 0, 1, 2)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_referente = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_referente.setFont(font)
        self.label_referente.setObjectName("label_referente")
        self.horizontalLayout_6.addWidget(self.label_referente)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem23)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.line = QtWidgets.QFrame(self.tab2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_nome = QtWidgets.QLabel(self.tab2)
        self.label_nome.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nome.setObjectName("label_nome")
        self.horizontalLayout_2.addWidget(self.label_nome)
        self.lineEdit_nome = MyLineEdit(self.tab2)
        self.lineEdit_nome.setMinimumSize(QtCore.QSize(256, 21))
        self.lineEdit_nome.setMaximumSize(QtCore.QSize(256, 21))
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.horizontalLayout_2.addWidget(self.lineEdit_nome)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem24)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_cognome = MyLineEdit(self.tab2)
        self.lineEdit_cognome.setMinimumSize(QtCore.QSize(256, 21))
        self.lineEdit_cognome.setMaximumSize(QtCore.QSize(256, 21))
        self.lineEdit_cognome.setObjectName("lineEdit_cognome")
        self.horizontalLayout_3.addWidget(self.lineEdit_cognome)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem25)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.tab2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_telefono = MyLineEdit(self.tab2)
        self.lineEdit_telefono.setMinimumSize(QtCore.QSize(256, 21))
        self.lineEdit_telefono.setMaximumSize(QtCore.QSize(256, 21))
        self.lineEdit_telefono.setObjectName("lineEdit_telefono")
        self.horizontalLayout_4.addWidget(self.lineEdit_telefono)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_email = QtWidgets.QLabel(self.tab2)
        self.label_email.setAlignment(QtCore.Qt.AlignCenter)
        self.label_email.setObjectName("label_email")
        self.horizontalLayout_27.addWidget(self.label_email)
        self.lineEdit_email = MyLineEdit(self.tab2)
        self.lineEdit_email.setMinimumSize(QtCore.QSize(256, 21))
        self.lineEdit_email.setMaximumSize(QtCore.QSize(256, 21))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.horizontalLayout_27.addWidget(self.lineEdit_email)
        self.verticalLayout.addLayout(self.horizontalLayout_27)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        self.horizontalLayout_19.addLayout(self.verticalLayout_6)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem27)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, 43, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.combo_platformPrenotazioni = QtWidgets.QComboBox(self.tab2)
        self.combo_platformPrenotazioni.setObjectName("combo_platformPrenotazioni")
        self.horizontalLayout_5.addWidget(self.combo_platformPrenotazioni)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, -1, 43, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        self.combo_stagionePrenotazioni = QtWidgets.QComboBox(self.tab2)
        self.combo_stagionePrenotazioni.setObjectName("combo_stagionePrenotazioni")
        self.combo_stagionePrenotazioni.addItem("")
        self.combo_stagionePrenotazioni.addItem("")
        self.combo_stagionePrenotazioni.addItem("")
        self.horizontalLayout_11.addWidget(self.combo_stagionePrenotazioni)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_5 = QtWidgets.QLabel(self.tab2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_18.addWidget(self.label_5)
        self.dateEdit_dal = MyDateEdit(self.tab2)
        self.dateEdit_dal.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 7, 14), QtCore.QTime(0, 0, 0)))
        self.dateEdit_dal.setMinimumDate(QtCore.QDate(2019, 7, 14))
        self.dateEdit_dal.setObjectName("dateEdit_dal")
        self.horizontalLayout_18.addWidget(self.dateEdit_dal)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem28)
        self.label_6 = QtWidgets.QLabel(self.tab2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_18.addWidget(self.label_6)
        self.dateEdit_al = MyDateEdit(self.tab2)
        self.dateEdit_al.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 7, 14), QtCore.QTime(0, 0, 0)))
        self.dateEdit_al.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2019, 7, 14), QtCore.QTime(0, 0, 0)))
        self.dateEdit_al.setObjectName("dateEdit_al")
        self.horizontalLayout_18.addWidget(self.dateEdit_al)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem29)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19.addLayout(self.verticalLayout_7)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_19.addLayout(self.verticalLayout_13)
        self.gridLayout_2.addLayout(self.horizontalLayout_19, 0, 0, 1, 2)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_8 = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_13.addWidget(self.label_8)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem30)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab2, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.main_page)
        self.gridLayout_3.addWidget(self.stackedWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 887, 25))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.label_9.setBuddy(self.spinBox_ospiti)
        self.label_10.setBuddy(self.spinBox_bambini)
        self.label.setBuddy(self.spinBox_importo)
        self.label_12.setBuddy(self.plainTextEdit_note)
        self.label_13.setBuddy(self.lineEdit_lordo)
        self.label_16.setBuddy(self.lineEdit_netto)
        self.label_17.setBuddy(self.lineEdit_tax)
        self.label_18.setBuddy(self.lineEdit_tax)
        self.label_nome.setBuddy(self.lineEdit_nome)
        self.label_3.setBuddy(self.lineEdit_cognome)
        self.label_4.setBuddy(self.lineEdit_telefono)
        self.label_email.setBuddy(self.lineEdit_email)
        self.label_5.setBuddy(self.dateEdit_dal)
        self.label_6.setBuddy(self.dateEdit_al)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Prenotazione"))
        item = self.tableWidget_info_ospite.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.tableWidget_info_ospite.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cognome"))
        item = self.tableWidget_info_ospite.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "#ospiti"))
        item = self.tableWidget_info_ospite.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "bambini"))
        item = self.tableWidget_info_ospite.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "numero notti"))
        item = self.tableWidget_info_ospite.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "In-->Out"))
        item = self.tableWidget_info_ospite.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_info_ospite.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        self.label_2.setText(_translate("MainWindow", "Statistiche"))
        item = self.tableWidget_stat.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "3 Notti"))
        item = self.tableWidget_stat.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2 Notti"))
        item = self.tableWidget_stat.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "1 Notte"))
        item = self.tableWidget_stat.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Totale Ospiti"))
        item = self.tableWidget_stat.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Netto mensile"))
        item = self.tableWidget_stat.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Spese mensili"))
        item = self.tableWidget_stat.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_stat.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        self.bot_spese.setText(_translate("MainWindow", "Spese"))
        self.bot_note.setText(_translate("MainWindow", "Note"))
        self.label_15.setText(_translate("MainWindow", "Stagione:"))
        self.label_stagione.setText(_translate("MainWindow", "Disconnesso"))
        self.bot_cancella.setText(_translate("MainWindow", "Cancella Prenotazione"))
        self.bot_prenota.setText(_translate("MainWindow", "Prenota"))
        self.bot_esporta.setText(_translate("MainWindow", "Esporta"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Calendario"))
        self.label_9.setText(_translate("MainWindow", "Numero:"))
        self.label_10.setText(_translate("MainWindow", "Bambini"))
        self.radio_colazione.setText(_translate("MainWindow", "colazione"))
        self.label.setText(_translate("MainWindow", "Importo:"))
        self.label_12.setText(_translate("MainWindow", "NOTE:"))
        self.label_13.setText(_translate("MainWindow", "Lordo"))
        self.label_16.setText(_translate("MainWindow", "Netto"))
        self.label_17.setText(_translate("MainWindow", "Numero giorni"))
        self.label_18.setText(_translate("MainWindow", "Tax"))
        self.bot_modifica.setText(_translate("MainWindow", "Modifica"))
        self.bot_salva.setText(_translate("MainWindow", "salva"))
        self.bot_annulla.setText(_translate("MainWindow", "annulla"))
        self.bot_checkDisp.setText(_translate("MainWindow", "disponnibilità"))
        self.label_referente.setText(_translate("MainWindow", "Referente"))
        self.label_nome.setText(_translate("MainWindow", "Nome:"))
        self.lineEdit_nome.setText(_translate("MainWindow", "lineEdit_nome"))
        self.label_3.setText(_translate("MainWindow", "cognome:"))
        self.lineEdit_cognome.setText(_translate("MainWindow", "lineEdit_cognome"))
        self.label_4.setText(_translate("MainWindow", "telefono:"))
        self.lineEdit_telefono.setText(_translate("MainWindow", "lineEdit_telefono"))
        self.label_email.setText(_translate("MainWindow", "email:"))
        self.lineEdit_email.setText(_translate("MainWindow", "lineEdit_email"))
        self.label_11.setText(_translate("MainWindow", "Platform :"))
        self.label_14.setText(_translate("MainWindow", "Stagione :"))
        self.combo_stagionePrenotazioni.setItemText(0, _translate("MainWindow", "Alta"))
        self.combo_stagionePrenotazioni.setItemText(1, _translate("MainWindow", "Media"))
        self.combo_stagionePrenotazioni.setItemText(2, _translate("MainWindow", "Bassa"))
        self.label_5.setText(_translate("MainWindow", "dal:"))
        self.label_6.setText(_translate("MainWindow", "al:"))
        self.label_8.setText(_translate("MainWindow", "Ospiti"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "Prenota"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))


from kwidget.mydateedit.mydateedit import MyDateEdit
from kwidget.mylineEdit.mylineEdit import MyLineEdit
from kwidget.myprogressbutton.myprogressbutton_main import ColorButton
from kwidget.waiting_spinner.waitingspinnerwidget import MySp


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
