# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_option.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_opt(object):
    def setupUi(self, Dialog_opt):
        Dialog_opt.setObjectName("Dialog_opt")
        Dialog_opt.setWindowModality(QtCore.Qt.WindowModal)
        Dialog_opt.resize(571, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_opt.sizePolicy().hasHeightForWidth())
        Dialog_opt.setSizePolicy(sizePolicy)
        Dialog_opt.setMinimumSize(QtCore.QSize(571, 500))
        Dialog_opt.setMaximumSize(QtCore.QSize(571, 385))
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog_opt)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(Dialog_opt)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_struttura_2 = QtWidgets.QWidget()
        self.tab_struttura_2.setObjectName("tab_struttura_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_struttura_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab_struttura_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.line_7 = QtWidgets.QFrame(self.tab_struttura_2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_9.addWidget(self.line_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.combo_stagione = QtWidgets.QComboBox(self.tab_struttura_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_stagione.sizePolicy().hasHeightForWidth())
        self.combo_stagione.setSizePolicy(sizePolicy)
        self.combo_stagione.setMinimumSize(QtCore.QSize(61, 23))
        self.combo_stagione.setMaximumSize(QtCore.QSize(61, 23))
        self.combo_stagione.setObjectName("combo_stagione")
        self.combo_stagione.addItem("")
        self.combo_stagione.addItem("")
        self.combo_stagione.addItem("")
        self.verticalLayout_10.addWidget(self.combo_stagione)
        self.horizontalLayout_10.addLayout(self.verticalLayout_10)
        self.verticalLayout_9.addLayout(self.horizontalLayout_10)
        self.gridLayout_2.addLayout(self.verticalLayout_9, 1, 0, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.line_8 = QtWidgets.QFrame(self.tab_struttura_2)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_12.addWidget(self.line_8)
        self.label_7 = QtWidgets.QLabel(self.tab_struttura_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_12.addWidget(self.label_7)
        self.verticalLayout_11.addLayout(self.verticalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.tab_struttura_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(81, 20))
        self.label_11.setMaximumSize(QtCore.QSize(81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.label_numeroLetti = QtWidgets.QLabel(self.tab_struttura_2)
        self.label_numeroLetti.setObjectName("label_numeroLetti")
        self.horizontalLayout_12.addWidget(self.label_numeroLetti)
        self.verticalLayout_13.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.bot_sottraiLetto = QtWidgets.QPushButton(self.tab_struttura_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_sottraiLetto.sizePolicy().hasHeightForWidth())
        self.bot_sottraiLetto.setSizePolicy(sizePolicy)
        self.bot_sottraiLetto.setMinimumSize(QtCore.QSize(21, 23))
        self.bot_sottraiLetto.setMaximumSize(QtCore.QSize(21, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bot_sottraiLetto.setFont(font)
        self.bot_sottraiLetto.setStyleSheet("\n"
"                                                    font:rgba(126, 240, 87, 229);\n"
"                                                ")
        self.bot_sottraiLetto.setObjectName("bot_sottraiLetto")
        self.horizontalLayout_13.addWidget(self.bot_sottraiLetto)
        self.bot_aggiungiLetto = QtWidgets.QPushButton(self.tab_struttura_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_aggiungiLetto.sizePolicy().hasHeightForWidth())
        self.bot_aggiungiLetto.setSizePolicy(sizePolicy)
        self.bot_aggiungiLetto.setMinimumSize(QtCore.QSize(21, 23))
        self.bot_aggiungiLetto.setMaximumSize(QtCore.QSize(21, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bot_aggiungiLetto.setFont(font)
        self.bot_aggiungiLetto.setStyleSheet("\n"
"                                                    font:rgba(126, 240, 87, 229);\n"
"                                                ")
        self.bot_aggiungiLetto.setObjectName("bot_aggiungiLetto")
        self.horizontalLayout_13.addWidget(self.bot_aggiungiLetto)
        self.verticalLayout_13.addLayout(self.horizontalLayout_13)
        self.line_9 = QtWidgets.QFrame(self.tab_struttura_2)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_13.addWidget(self.line_9)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.tab_struttura_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(81, 20))
        self.label_12.setMaximumSize(QtCore.QSize(81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_15.addWidget(self.label_12)
        self.spinbox_provvigione = QtWidgets.QDoubleSpinBox(self.tab_struttura_2)
        self.spinbox_provvigione.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinbox_provvigione.sizePolicy().hasHeightForWidth())
        self.spinbox_provvigione.setSizePolicy(sizePolicy)
        self.spinbox_provvigione.setMinimumSize(QtCore.QSize(65, 20))
        self.spinbox_provvigione.setMaximumSize(QtCore.QSize(65, 20))
        self.spinbox_provvigione.setAlignment(QtCore.Qt.AlignCenter)
        self.spinbox_provvigione.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinbox_provvigione.setMinimum(0.0)
        self.spinbox_provvigione.setMaximum(100.0)
        self.spinbox_provvigione.setSingleStep(1.0)
        self.spinbox_provvigione.setProperty("value", 0.0)
        self.spinbox_provvigione.setObjectName("spinbox_provvigione")
        self.horizontalLayout_15.addWidget(self.spinbox_provvigione)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_15)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.verticalLayout_13.addLayout(self.horizontalLayout_14)
        self.line_10 = QtWidgets.QFrame(self.tab_struttura_2)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_13.addWidget(self.line_10)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.tab_struttura_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(81, 20))
        self.label_13.setMaximumSize(QtCore.QSize(81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        self.spinbox_tasse = QtWidgets.QDoubleSpinBox(self.tab_struttura_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinbox_tasse.sizePolicy().hasHeightForWidth())
        self.spinbox_tasse.setSizePolicy(sizePolicy)
        self.spinbox_tasse.setMinimumSize(QtCore.QSize(65, 20))
        self.spinbox_tasse.setMaximumSize(QtCore.QSize(65, 20))
        self.spinbox_tasse.setAlignment(QtCore.Qt.AlignCenter)
        self.spinbox_tasse.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinbox_tasse.setMinimum(0.0)
        self.spinbox_tasse.setMaximum(100.0)
        self.spinbox_tasse.setSingleStep(1.0)
        self.spinbox_tasse.setProperty("value", 0.0)
        self.spinbox_tasse.setObjectName("spinbox_tasse")
        self.horizontalLayout_16.addWidget(self.spinbox_tasse)
        self.radio_attivaTassa = QtWidgets.QRadioButton(self.tab_struttura_2)
        self.radio_attivaTassa.setObjectName("radio_attivaTassa")
        self.horizontalLayout_16.addWidget(self.radio_attivaTassa)
        self.verticalLayout_13.addLayout(self.horizontalLayout_16)
        self.line_11 = QtWidgets.QFrame(self.tab_struttura_2)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_13.addWidget(self.line_11)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_14 = QtWidgets.QLabel(self.tab_struttura_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(81, 20))
        self.label_14.setMaximumSize(QtCore.QSize(81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_17.addWidget(self.label_14)
        self.bot_scegliColore = QtWidgets.QPushButton(self.tab_struttura_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_scegliColore.sizePolicy().hasHeightForWidth())
        self.bot_scegliColore.setSizePolicy(sizePolicy)
        self.bot_scegliColore.setMinimumSize(QtCore.QSize(55, 13))
        self.bot_scegliColore.setMaximumSize(QtCore.QSize(55, 13))
        self.bot_scegliColore.setStyleSheet("")
        self.bot_scegliColore.setText("")
        self.bot_scegliColore.setObjectName("bot_scegliColore")
        self.horizontalLayout_17.addWidget(self.bot_scegliColore)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem2)
        self.verticalLayout_13.addLayout(self.horizontalLayout_17)
        self.line_12 = QtWidgets.QFrame(self.tab_struttura_2)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_13.addWidget(self.line_12)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem3)
        self.horizontalLayout_11.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_15 = QtWidgets.QLabel(self.tab_struttura_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(81, 20))
        self.label_15.setMaximumSize(QtCore.QSize(81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_18.addWidget(self.label_15)
        self.combo_platform = QtWidgets.QComboBox(self.tab_struttura_2)
        self.combo_platform.setObjectName("combo_platform")
        self.combo_platform.addItem("")
        self.combo_platform.addItem("")
        self.combo_platform.addItem("")
        self.horizontalLayout_18.addWidget(self.combo_platform)
        self.verticalLayout_14.addLayout(self.horizontalLayout_18)
        self.tableWidget__importi = QtWidgets.QTableWidget(self.tab_struttura_2)
        self.tableWidget__importi.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableWidget__importi.setDragDropOverwriteMode(False)
        self.tableWidget__importi.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget__importi.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget__importi.setShowGrid(True)
        self.tableWidget__importi.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget__importi.setWordWrap(False)
        self.tableWidget__importi.setCornerButtonEnabled(False)
        self.tableWidget__importi.setRowCount(1)
        self.tableWidget__importi.setColumnCount(2)
        self.tableWidget__importi.setObjectName("tableWidget__importi")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget__importi.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget__importi.setHorizontalHeaderItem(1, item)
        self.tableWidget__importi.horizontalHeader().setVisible(False)
        self.tableWidget__importi.horizontalHeader().setHighlightSections(False)
        self.tableWidget__importi.horizontalHeader().setMinimumSectionSize(70)
        self.tableWidget__importi.horizontalHeader().setStretchLastSection(True)
        self.tableWidget__importi.verticalHeader().setVisible(False)
        self.verticalLayout_14.addWidget(self.tableWidget__importi)
        self.horizontalLayout_11.addLayout(self.verticalLayout_14)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.gridLayout_2.addLayout(self.verticalLayout_11, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_struttura_2, "")
        self.tab_connessione_2 = QtWidgets.QWidget()
        self.tab_connessione_2.setEnabled(True)
        self.tab_connessione_2.setObjectName("tab_connessione_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_connessione_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_21 = QtWidgets.QLabel(self.tab_connessione_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(92, 20))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_24.addWidget(self.label_21)
        self.lineEdit_host = QtWidgets.QLineEdit(self.tab_connessione_2)
        self.lineEdit_host.setObjectName("lineEdit_host")
        self.horizontalLayout_24.addWidget(self.lineEdit_host)
        self.gridLayout_6.addLayout(self.horizontalLayout_24, 0, 0, 1, 1)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_22 = QtWidgets.QLabel(self.tab_connessione_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(92, 20))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_25.addWidget(self.label_22)
        self.lineEdit_port = QtWidgets.QLineEdit(self.tab_connessione_2)
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.horizontalLayout_25.addWidget(self.lineEdit_port)
        self.gridLayout_6.addLayout(self.horizontalLayout_25, 1, 0, 1, 1)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_23 = QtWidgets.QLabel(self.tab_connessione_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(92, 20))
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_26.addWidget(self.label_23)
        self.lineEdit_user = QtWidgets.QLineEdit(self.tab_connessione_2)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.horizontalLayout_26.addWidget(self.lineEdit_user)
        self.gridLayout_6.addLayout(self.horizontalLayout_26, 2, 0, 1, 1)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_24 = QtWidgets.QLabel(self.tab_connessione_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(92, 20))
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_27.addWidget(self.label_24)
        self.lineEdit_password = QtWidgets.QLineEdit(self.tab_connessione_2)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout_27.addWidget(self.lineEdit_password)
        self.gridLayout_6.addLayout(self.horizontalLayout_27, 3, 0, 1, 1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_25 = QtWidgets.QLabel(self.tab_connessione_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(92, 20))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_28.addWidget(self.label_25)
        self.lineEdit_nome_db = QtWidgets.QLineEdit(self.tab_connessione_2)
        self.lineEdit_nome_db.setObjectName("lineEdit_nome_db")
        self.horizontalLayout_28.addWidget(self.lineEdit_nome_db)
        self.gridLayout_6.addLayout(self.horizontalLayout_28, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab_connessione_2, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_opt)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_8.addWidget(self.buttonBox)
        spacerItem4 = QtWidgets.QSpacerItem(72, 177, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.gridLayout_4.addLayout(self.verticalLayout_8, 0, 1, 1, 1)
        self.label_21.setBuddy(self.lineEdit_host)
        self.label_22.setBuddy(self.lineEdit_port)
        self.label_23.setBuddy(self.lineEdit_user)
        self.label_24.setBuddy(self.lineEdit_password)
        self.label_25.setBuddy(self.lineEdit_nome_db)

        self.retranslateUi(Dialog_opt)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog_opt.accept)
        self.buttonBox.rejected.connect(Dialog_opt.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_opt)

    def retranslateUi(self, Dialog_opt):
        _translate = QtCore.QCoreApplication.translate
        Dialog_opt.setWindowTitle(_translate("Dialog_opt", "EvInterface -Configurazione"))
        self.label_2.setText(_translate("Dialog_opt", "Stagione"))
        self.combo_stagione.setItemText(0, _translate("Dialog_opt", "Alta"))
        self.combo_stagione.setItemText(1, _translate("Dialog_opt", "Media"))
        self.combo_stagione.setItemText(2, _translate("Dialog_opt", "Bassa"))
        self.label_7.setText(_translate("Dialog_opt", "Importi"))
        self.label_11.setText(_translate("Dialog_opt", "Numero Letti:"))
        self.label_numeroLetti.setText(_translate("Dialog_opt", "TextLabel"))
        self.bot_sottraiLetto.setText(_translate("Dialog_opt", "-"))
        self.bot_aggiungiLetto.setText(_translate("Dialog_opt", "+"))
        self.label_12.setText(_translate("Dialog_opt", "Provvigione:"))
        self.spinbox_provvigione.setSuffix(_translate("Dialog_opt", "%"))
        self.label_13.setText(_translate("Dialog_opt", "Tasse:"))
        self.spinbox_tasse.setSuffix(_translate("Dialog_opt", "€"))
        self.radio_attivaTassa.setText(_translate("Dialog_opt", "Attiva"))
        self.label_14.setText(_translate("Dialog_opt", "Colore"))
        self.label_15.setText(_translate("Dialog_opt", "Platform:"))
        self.combo_platform.setItemText(0, _translate("Dialog_opt", "Booking"))
        self.combo_platform.setItemText(1, _translate("Dialog_opt", "AirB&B"))
        self.combo_platform.setItemText(2, _translate("Dialog_opt", "Privati"))
        self.tableWidget__importi.setToolTip(_translate("Dialog_opt", "Doppio click su una riga per impostare il\n"
"                                                                    prezzo\n"
"                                                                "))
        item = self.tableWidget__importi.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_opt", "Numero Letti"))
        item = self.tableWidget__importi.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_opt", "€"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_struttura_2), _translate("Dialog_opt", "Struttura"))
        self.label_21.setText(_translate("Dialog_opt", "Host:"))
        self.label_22.setText(_translate("Dialog_opt", "Port:"))
        self.label_23.setText(_translate("Dialog_opt", "User:"))
        self.label_24.setText(_translate("Dialog_opt", "Password:"))
        self.label_25.setText(_translate("Dialog_opt", "Nome Database:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_connessione_2), _translate("Dialog_opt", "Connessione"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_opt = QtWidgets.QDialog()
    ui = Ui_Dialog_opt()
    ui.setupUi(Dialog_opt)
    Dialog_opt.show()
    sys.exit(app.exec_())
