# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_calendar.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalendarTableWid(object):
    def setupUi(self, CalendarTableWid):
        CalendarTableWid.setObjectName("CalendarTableWid")
        CalendarTableWid.resize(624, 526)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CalendarTableWid.sizePolicy().hasHeightForWidth())
        CalendarTableWid.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(CalendarTableWid)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bot_prev = QtWidgets.QPushButton(CalendarTableWid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_prev.sizePolicy().hasHeightForWidth())
        self.bot_prev.setSizePolicy(sizePolicy)
        self.bot_prev.setMinimumSize(QtCore.QSize(40, 40))
        self.bot_prev.setMaximumSize(QtCore.QSize(40, 40))
        self.bot_prev.setStyleSheet("border-image: url(:/bots/prevPageIcon.png);")
        self.bot_prev.setText("")
        self.bot_prev.setObjectName("bot_prev")
        self.horizontalLayout.addWidget(self.bot_prev)
        self.combo_mesi = ComboSenzaFreccia(CalendarTableWid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_mesi.sizePolicy().hasHeightForWidth())
        self.combo_mesi.setSizePolicy(sizePolicy)
        self.combo_mesi.setMinimumSize(QtCore.QSize(0, 40))
        self.combo_mesi.setMaximumSize(QtCore.QSize(16777215, 40))
        self.combo_mesi.setObjectName("combo_mesi")
        self.combo_mesi.addItem("")
        self.combo_mesi.addItem("")
        self.combo_mesi.addItem("")
        self.combo_mesi.addItem("")
        self.combo_mesi.addItem("")
        self.combo_mesi.addItem("")
        self.combo_mesi.addItem("")
        self.combo_mesi.addItem("")
        self.combo_mesi.addItem("")
        self.combo_mesi.addItem("")
        self.combo_mesi.addItem("")
        self.combo_mesi.addItem("")
        self.horizontalLayout.addWidget(self.combo_mesi)
        self.bot_next = QtWidgets.QPushButton(CalendarTableWid)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_next.sizePolicy().hasHeightForWidth())
        self.bot_next.setSizePolicy(sizePolicy)
        self.bot_next.setMinimumSize(QtCore.QSize(40, 40))
        self.bot_next.setMaximumSize(QtCore.QSize(40, 40))
        self.bot_next.setStyleSheet("border-image: url(:/bots/nextPageIcon.png);")
        self.bot_next.setText("")
        self.bot_next.setObjectName("bot_next")
        self.horizontalLayout.addWidget(self.bot_next)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.table = QtWidgets.QTableWidget(CalendarTableWid)
        self.table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.table.setFrameShadow(QtWidgets.QFrame.Plain)
        self.table.setLineWidth(0)
        self.table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table.setAutoScroll(False)
        self.table.setTabKeyNavigation(False)
        self.table.setProperty("showDropIndicator", False)
        self.table.setDragDropOverwriteMode(False)
        self.table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table.setWordWrap(False)
        self.table.setCornerButtonEnabled(False)
        self.table.setRowCount(0)
        self.table.setColumnCount(0)
        self.table.setObjectName("table")
        self.table.verticalHeader().setVisible(False)
        self.table.verticalHeader().setMinimumSectionSize(44)
        self.verticalLayout.addWidget(self.table)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.label_anno = QtWidgets.QLabel(CalendarTableWid)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_anno.setFont(font)
        self.label_anno.setAlignment(QtCore.Qt.AlignCenter)
        self.label_anno.setObjectName("label_anno")
        self.gridLayout.addWidget(self.label_anno, 0, 0, 1, 1)

        self.retranslateUi(CalendarTableWid)
        QtCore.QMetaObject.connectSlotsByName(CalendarTableWid)

    def retranslateUi(self, CalendarTableWid):
        _translate = QtCore.QCoreApplication.translate
        CalendarTableWid.setWindowTitle(_translate("CalendarTableWid", "Form"))
        self.combo_mesi.setItemText(0, _translate("CalendarTableWid", "Gennaio"))
        self.combo_mesi.setItemText(1, _translate("CalendarTableWid", "Febbraio"))
        self.combo_mesi.setItemText(2, _translate("CalendarTableWid", "Marzo"))
        self.combo_mesi.setItemText(3, _translate("CalendarTableWid", "Aprile"))
        self.combo_mesi.setItemText(4, _translate("CalendarTableWid", "Maggio"))
        self.combo_mesi.setItemText(5, _translate("CalendarTableWid", "Giugno"))
        self.combo_mesi.setItemText(6, _translate("CalendarTableWid", "Luglio"))
        self.combo_mesi.setItemText(7, _translate("CalendarTableWid", "Agosto"))
        self.combo_mesi.setItemText(8, _translate("CalendarTableWid", "Settembre"))
        self.combo_mesi.setItemText(9, _translate("CalendarTableWid", "Ottobre"))
        self.combo_mesi.setItemText(10, _translate("CalendarTableWid", "Novembre"))
        self.combo_mesi.setItemText(11, _translate("CalendarTableWid", "Dicembre"))
        self.label_anno.setText(_translate("CalendarTableWid", "Anno: "))


from kwidget.combosenzafreccia.combosenzafreccia import ComboSenzaFreccia
import Icons.iconeBot


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CalendarTableWid = QtWidgets.QWidget()
    ui = Ui_CalendarTableWid()
    ui.setupUi(CalendarTableWid)
    CalendarTableWid.show()
    sys.exit(app.exec_())
