# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'complex_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_complexLabel(object):
    def setupUi(self, complexLabel):
        complexLabel.setObjectName("complexLabel")
        complexLabel.resize(211, 148)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(complexLabel.sizePolicy().hasHeightForWidth())
        complexLabel.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(complexLabel)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lab_num = QtWidgets.QLabel(complexLabel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_num.sizePolicy().hasHeightForWidth())
        self.lab_num.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lab_num.setFont(font)
        self.lab_num.setStyleSheet("background-color: rgba(170, 255, 127, 150);")
        self.lab_num.setText("")
        self.lab_num.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_num.setObjectName("lab_num")
        self.verticalLayout_4.addWidget(self.lab_num)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.labSpese = SquaredLabel(complexLabel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labSpese.sizePolicy().hasHeightForWidth())
        self.labSpese.setSizePolicy(sizePolicy)
        self.labSpese.setMinimumSize(QtCore.QSize(16, 16))
        self.labSpese.setMaximumSize(QtCore.QSize(64, 64))
        self.labSpese.setStyleSheet("")
        self.labSpese.setText("")
        self.labSpese.setScaledContents(True)
        self.labSpese.setAlignment(QtCore.Qt.AlignCenter)
        self.labSpese.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.labSpese.setObjectName("labSpese")
        self.verticalLayout.addWidget(self.labSpese)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem4)
        self.labNote = SquaredLabel(complexLabel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labNote.sizePolicy().hasHeightForWidth())
        self.labNote.setSizePolicy(sizePolicy)
        self.labNote.setMinimumSize(QtCore.QSize(16, 16))
        self.labNote.setMaximumSize(QtCore.QSize(64, 64))
        self.labNote.setStyleSheet("")
        self.labNote.setText("")
        self.labNote.setScaledContents(True)
        self.labNote.setAlignment(QtCore.Qt.AlignCenter)
        self.labNote.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.labNote.setObjectName("labNote")
        self.verticalLayout_2.addWidget(self.labNote)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.horizontalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem7)
        self.labCleaning = SquaredLabel(complexLabel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labCleaning.sizePolicy().hasHeightForWidth())
        self.labCleaning.setSizePolicy(sizePolicy)
        self.labCleaning.setMinimumSize(QtCore.QSize(16, 16))
        self.labCleaning.setMaximumSize(QtCore.QSize(64, 64))
        self.labCleaning.setStyleSheet("")
        self.labCleaning.setText("")
        self.labCleaning.setScaledContents(True)
        self.labCleaning.setAlignment(QtCore.Qt.AlignCenter)
        self.labCleaning.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.labCleaning.setObjectName("labCleaning")
        self.verticalLayout_3.addWidget(self.labCleaning)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.horizontalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)

        self.retranslateUi(complexLabel)
        QtCore.QMetaObject.connectSlotsByName(complexLabel)

    def retranslateUi(self, complexLabel):
        _translate = QtCore.QCoreApplication.translate
        complexLabel.setWindowTitle(_translate("complexLabel", "Form"))
from squaredLabel import SquaredLabel


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    complexLabel = QtWidgets.QWidget()
    ui = Ui_complexLabel()
    ui.setupUi(complexLabel)
    complexLabel.show()
    sys.exit(app.exec_())
